### ISSUE TITLE
When run your code , Here are some problems

### ISSUE THREAD

**Issue by sshzhang** [chentingpc/NNCF#1]
/PycharmProjects/NNCF/sampler$ ./make.sh
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from Cython.Build import cythonize
ImportError: No module named Cython.Build
rm: 无法删除'sampler.cpp': 没有那个文件或目录
rm: 无法删除'build': 没有那个文件或目录
zxj@zxj:~/PycharmProjects/NNCF/sampler$ cd ..
zxj@zxj:~/PycharmProjects/NNCF$ cd scripts/
zxj@zxj:~/PycharmProjects/NNCF/scripts$ cd demos/
zxj@zxj:~/PycharmProjects/NNCF/scripts/demos$ ./run_neg_shared.sh 
******, neg_shared, cnn_embedding, citeulike_title_and_abstract, skip-gram, 512, 0.01, unigram
Using Theano backend.
WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
Traceback (most recent call last):
  File "main.py", line 54, in <module>
    from configs.cnn_embedding_conf import get_conf
  File "./configs/cnn_embedding_conf.py", line 5, in <module>
    from data_utils import get_pretrain_folder
  File "./configs/data_utils.py", line 9, in <module>
    from sampler import MultinomialSampler
ImportError: cannot import name MultinomialSampler

**Comment by chentingpc** [comment]
This is the import error from external packages, "ImportError: No module named Cython.Build". And it seems you need to install Cython.
